find_package(OpenMP REQUIRED)
IF (OPENMP_FOUND)
    if (MSVC)
        SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
    endif ()
    if (APPLE)
        include_directories(${OpenMP_CXX_INCLUDE_DIRS})
        link_libraries(${OpenMP_CXX_LIBRARIES})
    endif ()
ENDIF ()