#ifndef POSITIONBASEDDYNAMICS_POINT_NEIGHBOR_SEARCHER3_H
#define POSITIONBASEDDYNAMICS_POINT_NEIGHBOR_SEARCHER3_H

namespace HINASIM::UTILS
{

    class PointNeighborSearcher3
    {

    };

}

#endif //POSITIONBASEDDYNAMICS_POINT_NEIGHBOR_SEARCHER3_H
